---
title: "R Notebook"
output: html_notebook
---
 

```{r}
BiocManager::install("edgeR")

library('edgeR')
install.packages("statmod")
library('statmod')
library('org.Mm.eg.db')
BiocManager::install("org.Hs.eg.db")
```

```{r}
install.packages('BiocManager')
install.packages('RColorBrewer')
install.packages('pheatmap')

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")


BiocManager::install("DESeq2")
install.packages('genefilter')
````



```{r}
cancer_counts <- read.table(file="FEATURECOUNTS_HRT_LYMP.txt", sep = "\t", header = F)
head(cancer_counts)
```
```{r}

y <- DGEList(counts=cancer_counts[,2:7],genes=cancer_counts[,1])
```

```{r}
head(y$genes)
rownames(y$counts) <- rownames(y$genes) <- y$genes$ENTREZID
y$genes$ENTREZID <- NULL
head(y)
```

```{r}
y <- calcNormFactors(y)
head(y)
colnames(y)
colnames(y)=c("H1", "H2", "H3", "L1", "L2", "L3")
```

```{r}
y$samples$group = c("H", "H", "H", "L", "L", "L")
plotMDS(y)
```

```{r}
y <- estimateDisp(y)
y
```


```{r}
plotBCV(y)
```


```{r}
et <- exactTest(y, pair=c("H","L"))
summary(de <- decideTestsDGE(et))
de <- decideTestsDGE(et)

et
```


```{r}



de.genes <- rownames(topTags(et, n=1200)$table)

plotSmear(et, de.tags=de.genes)
abline(h=c(-1, 1), col="blue")
```

```{r}
diffExpGenes <- topTags(et, n=1000, p.value = 0.05)
head(diffExpGenes$table)
```

```{r}
write.table(diffExpGenes$table, file="heart_v_lymp_exactTest.txt", sep = "\t", row.names=TRUE, col.names=NA)
```

```{r}
topGenesHeatmap <- pheatmap(y, annotation_col=df, labels_col = 10)

```

```{r}
y

```

